In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv("tmdb_movies_data.csv")
df.head()

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015,137999939.3,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015,137999939.3,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015,101199955.5,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015,183999919.0,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015,174799923.1,1.385749e+09

In [3]:
df.describe()

,id,popularity,budget,revenue,runtime,vote_count,vote_average,release_year,budget_adj,revenue_adj
count,10866.000000,10866.000000,1.086600e+04,1.086600e+04,10866.000000,10866.000000,10866.000000,10866.000000,1.086600e+04,1.086600e+04
mean,66064.177434,0.646441,1.462570e+07,3.982332e+07,102.070863,217.389748,5.974922,2001.322658,1.755104e+07,5.136436e+07
std,92130.136561,1.000185,3.091321e+07,1.170035e+08,31.381405,575.619058,0.935142,12.812941,3.430616e+07,1.446325e+08
min,5.000000,0.000065,0.000000e+00,0.000000e+00,0.000000,10.000000,1.500000,1960.000000,0.000000e+00,0.000000e+00
25%,10596.250000,0.207583,0.000000e+00,0.000000e+00,90.000000,17.000000,5.400000,1995.000000,0.000000e+00,0.000000e+00
50%,20669.000000,0.383856,0.000000e+00,0.000000e+00,99.000000,38.000000,6.000000,2006.000000,0.000000e+00,0.000000e+00
75%,75610.000000,0.713817,1.500000e+07,2.400000e+07,111.000000,145.750000,6.600000,2011.000000,2.085325e+07,3.369710e+07
max,417859.000000,32.985763,4.250000e+08,2.781506e+09,900.000000,9767.000000,9.200000,2015.000000,4.250000e+08,2.827124e+09

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10866 entries, 0 to 10865
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10866 non-null  int64
 1   imdb_id               10856 non-null  object
 2   popularity            10866 non-null  float64
 3   budget                10866 non-null  int64
 4   revenue               10866 non-null  int64
 5   original_title        10866 non-null  object
 6   cast                  10790 non-null  object
 7   homepage              2936 non-null   object
 8   director              10822 non-null  object
 9   tagline               8042 non-null   object
 10  keywords              9373 non-null   object
 11  overview              10862 non-null  object
 12  runtime               10866 non-null  int64
 13  genres                10843 non-null  object
 14  production_companies  9836 non-null   object
 15  release_date          10866 non-null  object
 16  vote_count            10866 non-null  int64
 17  vote_average          10866 non-null  float64
 18  release_year          10866 non-null  int64
 19  budget_adj            10866 non-null  float64
 20  revenue_adj           10866 non-null  float64
dtypes: float64(4), int64(6), object(11)
memory usage: 1.7+ MB

In [5]:
df.isnull().sum()

id                         0
imdb_id                   10
popularity                 0
budget                     0
revenue                    0
original_title             0
cast                      76
homepage                7930
director                  44
tagline                 2824
keywords                1493
overview                   4
runtime                    0
genres                    23
production_companies    1030
release_date               0
vote_count                 0
vote_average               0
release_year               0
budget_adj                 0
revenue_adj                0
dtype: int64

In [6]:
movies = df[['id','original_title','overview','genres']]

In [7]:
movies.head()

,id,original_title,overview,genres
0,135397,Jurassic World,Twenty-two years after the events of Jurassic ...,Action|Adventure|Science Fiction|Thriller
1,76341,Mad Max: Fury Road,An apocalyptic story set in the furthest reach...,Action|Adventure|Science Fiction|Thriller
2,262500,Insurgent,Beatrice Prior must confront her inner demons ...,Adventure|Science Fiction|Thriller
3,140607,Star Wars: The Force Awakens,Thirty years after defeating the Galactic Empi...,Action|Adventure|Science Fiction|Fantasy
4,168259,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,Action|Crime|Thriller

In [8]:
movies.isnull().sum()

id                 0
original_title     0
overview           4
genres            23
dtype: int64

In [9]:
movies['tags'] = movies['genres']+ ' ' + movies['overview']

C:\Users\HP\AppData\Local\Temp\ipykernel_25020\1632055600.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags'] = movies['genres']+ ' ' + movies['overview']

In [10]:
movies.head()

,id,original_title,overview,genres,tags
0,135397,Jurassic World,Twenty-two years after the events of Jurassic ...,Action|Adventure|Science Fiction|Thriller,Action|Adventure|Science Fiction|Thriller Twen...
1,76341,Mad Max: Fury Road,An apocalyptic story set in the furthest reach...,Action|Adventure|Science Fiction|Thriller,Action|Adventure|Science Fiction|Thriller An a...
2,262500,Insurgent,Beatrice Prior must confront her inner demons ...,Adventure|Science Fiction|Thriller,Adventure|Science Fiction|Thriller Beatrice Pr...
3,140607,Star Wars: The Force Awakens,Thirty years after defeating the Galactic Empi...,Action|Adventure|Science Fiction|Fantasy,Action|Adventure|Science Fiction|Fantasy Thirt...
4,168259,Furious 7,Deckard Shaw seeks revenge against Dominic Tor...,Action|Crime|Thriller,Action|Crime|Thriller Deckard Shaw seeks reven...

In [11]:
movies = movies.drop(columns = ['overview','genres'])

In [12]:
movies.head()

,id,original_title,tags
0,135397,Jurassic World,Action|Adventure|Science Fiction|Thriller Twen...
1,76341,Mad Max: Fury Road,Action|Adventure|Science Fiction|Thriller An a...
2,262500,Insurgent,Adventure|Science Fiction|Thriller Beatrice Pr...
3,140607,Star Wars: The Force Awakens,Action|Adventure|Science Fiction|Fantasy Thirt...
4,168259,Furious 7,Action|Crime|Thriller Deckard Shaw seeks reven...

In [13]:
from sklearn.feature_extraction.text import CountVectorizer

In [14]:
movies.shape

(10866, 3)

In [15]:
cv = CountVectorizer(max_features = 10866, stop_words = 'english')

In [16]:
cv

CountVectorizer(max_features=10866, stop_words='english')

In [17]:
vector = cv.fit_transform(movies['tags'].values.astype('U')).toarray()

In [18]:
vector.shape

(10866, 10866)

In [19]:
from sklearn.metrics.pairwise import cosine_similarity

In [20]:
similarity = cosine_similarity(vector)

In [21]:
similarity

array([[1.        , 0.2057378 , 0.19802951, ..., 0.        , 0.0758098 ,
        0.        ],
       [0.2057378 , 1.        , 0.12222647, ..., 0.        , 0.16376789,
        0.        ],
       [0.19802951, 0.12222647, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.03573708,
        0.        ],
       [0.0758098 , 0.16376789, 0.        , ..., 0.03573708, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [22]:
movies.head(20)

,id,original_title,tags
0,135397,Jurassic World,Action|Adventure|Science Fiction|Thriller Twen...
1,76341,Mad Max: Fury Road,Action|Adventure|Science Fiction|Thriller An a...
2,262500,Insurgent,Adventure|Science Fiction|Thriller Beatrice Pr...
3,140607,Star Wars: The Force Awakens,Action|Adventure|Science Fiction|Fantasy Thirt...
4,168259,Furious 7,Action|Crime|Thriller Deckard Shaw seeks reven...
5,281957,The Revenant,"Western|Drama|Adventure|Thriller In the 1820s,..."
6,87101,Terminator Genisys,Science Fiction|Action|Thriller|Adventure The ...
7,286217,The Martian,Drama|Adventure|Science Fiction During a manne...
8,211672,Minions,Family|Animation|Adventure|Comedy Minions Stua...
9,150540,Inside Out,Comedy|Animation|Family Growing up can be a bu...
10,206647,Spectre,Action|Adventure|Crime A cryptic message from ...
11,76757,Jupiter Ascending,Science Fiction|Fantasy|Action|Adventure In a ...
12,264660,Ex Machina,"Drama|Science Fiction Caleb, a 26 year old cod..."
13,257344,Pixels,Action|Comedy|Science Fiction Video game exper...
14,99861,Avengers: Age of Ultron,Action|Adventure|Science Fiction When Tony Sta...
15,273248,The Hateful Eight,Crime|Drama|Mystery|Western Bounty hunters see...
16,260346,Taken 3,Crime|Action|Thriller Ex-government operative ...
17,102899,Ant-Man,Science Fiction|Action|Adventure Armed with th...
18,150689,Cinderella,Romance|Fantasy|Family|Drama When her father u...
19,131634,The Hunger Games: Mockingjay - Part 2,War|Adventure|Science Fiction With the nation ...

In [41]:
movies[movies['original_title']=="Furious 7"].index[0]

4

In [51]:
distance = sorted(list(enumerate(similarity[4])),reverse = True, key = lambda vector:vector[1])
for i in distance[0:5]:
    print(movies.iloc[i[0]].original_title)

Furious 7
Savage Streets
Fast & Furious 6
Patriot Games
Transit

In [38]:
def recommend(movie):
    index = movies[movies['original_title']== movie].index[0]
    distance = sorted(list(enumerate(similarity[index])),reverse = True, key = lambda vector:vector[1])
    for i in distance[0:5]:
        print(movies.iloc[i[0]].original_title)

In [39]:
recommend('Taken 3')

Taken 3
Taken 2
Harry Brown
Blitz
Shooter

In [27]:
import pickle

In [28]:
pickle.dump(movies,open('movies_list.pkl','wb'))

In [60]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [61]:
pickle.load(open('movies_list.pkl','rb'))

,id,original_title,tags
0,135397,Jurassic World,Action|Adventure|Science Fiction|Thriller Twen...
1,76341,Mad Max: Fury Road,Action|Adventure|Science Fiction|Thriller An a...
2,262500,Insurgent,Adventure|Science Fiction|Thriller Beatrice Pr...
3,140607,Star Wars: The Force Awakens,Action|Adventure|Science Fiction|Fantasy Thirt...
4,168259,Furious 7,Action|Crime|Thriller Deckard Shaw seeks reven...
...,...,...,...
10861,21,The Endless Summer,"Documentary The Endless Summer, by Bruce Brown..."
10862,20379,Grand Prix,Action|Adventure|Drama Grand Prix driver Pete ...
10863,39768,Beregis Avtomobilya,Mystery|Comedy An insurance agent who moonligh...
10864,21449,"What's Up, Tiger Lily?",Action|Comedy In comic Woody Allen's film debu...
10865,22293,Manos: The Hands of Fate,Horror A family gets lost on the road and stum...

In [62]:
pickle.load(open('similarity.pkl','rb'))

array([[1.        , 0.2057378 , 0.19802951, ..., 0.        , 0.0758098 ,
        0.        ],
       [0.2057378 , 1.        , 0.12222647, ..., 0.        , 0.16376789,
        0.        ],
       [0.19802951, 0.12222647, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.03573708,
        0.        ],
       [0.0758098 , 0.16376789, 0.        , ..., 0.03573708, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])

In [45]:
movies[movies['original_title'] == "Jurassic World"].index[0]

0

In [49]:
movies[movies['original_title'] == "Insurgent"].id

2    262500
Name: id, dtype: int64

In [52]:
movies.iloc[2]

id                                                           262500
original_title                                            Insurgent
tags              Adventure|Science Fiction|Thriller Beatrice Pr...
Name: 2, dtype: object

In [53]:
distance = sorted(list(enumerate(similarity[4])),reverse = True, key = lambda vector:vector[1])
distance

[(4, 1.0000000000000002),
 (7949, 0.36563621206356534),
 (5650, 0.3458572319330373),
 (8277, 0.3458572319330373),
 (4757, 0.3344968040028364),
 (7721, 0.3344968040028364),
 (9999, 0.3344968040028364),
 (2753, 0.3249182166443294),
 (838, 0.3223291856101521),
 (7229, 0.3113995776646092),
 (9773, 0.3113995776646092),
 (4643, 0.3077287274483319),
 (6439, 0.30151134457776363),
 (8097, 0.30151134457776363),
 (10597, 0.30151134457776363),
 (9064, 0.2955402316445243),
 (9848, 0.2934695928267111),
 (3583, 0.29250896965085227),
 (4317, 0.29250896965085227),
 (9948, 0.29250896965085227),
 (1539, 0.28968272975116055),
 (65, 0.2860387767736777),
 (2083, 0.2860387767736777),
 (3505, 0.2860387767736777),
 (9430, 0.2860387767736777),
 (4603, 0.2842676218074806),
 (5662, 0.2842676218074806),
 (10493, 0.2842676218074806),
 (4431, 0.2799462554779271),
 (4581, 0.27668578554642986),
 (7951, 0.27668578554642986),
 (7269, 0.2758802939230217),
 (505, 0.27272727272727276),
 (555, 0.27272727272727276),
 (2950, 0.27272727272727276),
 (4475, 0.27272727272727276),
 (5070, 0.27272727272727276),
 (7440, 0.27272727272727276),
 (4498, 0.26967994498529685),
 (5644, 0.26967994498529685),
 (9418, 0.26967994498529685),
 (3266, 0.26673253468463226),
 (9216, 0.26673253468463226),
 (2327, 0.2631806779839076),
 (4421, 0.2631806779839076),
 (4974, 0.2631806779839076),
 (6210, 0.26243194054073904),
 (4322, 0.262431940540739),
 (1819, 0.2611164839335468),
 (4472, 0.2611164839335468),
 (5587, 0.2611164839335468),
 (7244, 0.2611164839335468),
 (7288, 0.2611164839335468),
 (7383, 0.2611164839335468),
 (8419, 0.2611164839335468),
 (6469, 0.2584382953523688),
 (5557, 0.25712973861328997),
 (6623, 0.25712973861328997),
 (8623, 0.25712973861328997),
 (684, 0.25482359571881275),
 (783, 0.2514778453847726),
 (6963, 0.2514778453847726),
 (5838, 0.251259453814803),
 (7378, 0.251259453814803),
 (8721, 0.251259453814803),
 (8786, 0.251259453814803),
 (734, 0.25087260300212727),
 (883, 0.25087260300212727),
 (3841, 0.25087260300212727),
 (4439, 0.25087260300212727),
 (4519, 0.25087260300212727),
 (5011, 0.25087260300212727),
 (6244, 0.25087260300212727),
 (6580, 0.25087260300212727),
 (6719, 0.25087260300212727),
 (7054, 0.25087260300212727),
 (8049, 0.25087260300212727),
 (8357, 0.25087260300212727),
 (8944, 0.25087260300212727),
 (9821, 0.25087260300212727),
 (799, 0.2461829819586655),
 (9984, 0.2461829819586655),
 (3619, 0.24455799402225925),
 (1262, 0.24455799402225922),
 (7112, 0.2417468892076141),
 (776, 0.24174688920761409),
 (1607, 0.24174688920761409),
 (2028, 0.24174688920761409),
 (2536, 0.24174688920761409),
 (2934, 0.24174688920761409),
 (3140, 0.24174688920761409),
 (4300, 0.24174688920761409),
 (4965, 0.24174688920761409),
 (6278, 0.24174688920761409),
 (6424, 0.24174688920761409),
 (7546, 0.24174688920761409),
 (8071, 0.24174688920761409),
 (9375, 0.24174688920761409),
 (10314, 0.24174688920761409),
 (7566, 0.24120907566221092),
 (3044, 0.2383656473113981),
 (3645, 0.2383656473113981),
 (473, 0.23354968324845687),
 (941, 0.23354968324845687),
 (1423, 0.23354968324845687),
 (1787, 0.23354968324845687),
 (2661, 0.23354968324845687),
 (2856, 0.23354968324845687),
 (4034, 0.23354968324845687),
 (4044, 0.23354968324845687),
 (5478, 0.23354968324845687),
 (5496, 0.23354968324845687),
 (5791, 0.23354968324845687),
 (7434, 0.23354968324845687),
 (7984, 0.23354968324845687),
 (8048, 0.23354968324845687),
 (8955, 0.23354968324845687),
 (9415, 0.23354968324845687),
 (9451, 0.23354968324845687),
 (10565, 0.23354968324845687),
 (8289, 0.2326210525996177),
 (5272, 0.2321035412742638),
 (7405, 0.2321035412742638),
 (2087, 0.2279211529192759),
 (5221, 0.2279211529192759),
 (10059, 0.2279211529192759),
 (1612, 0.22792115291927587),
 (1782, 0.22792115291927587),
 (3799, 0.22792115291927587),
 (8407, 0.22792115291927587),
 (9400, 0.22792115291927587),
 (1355, 0.22727272727272732),
 (122, 0.22613350843332272),
 (926, 0.22613350843332272),
 (1244, 0.22613350843332272),
 (1681, 0.22613350843332272),
 (1953, 0.22613350843332272),
 (2444, 0.22613350843332272),
 (2724, 0.22613350843332272),
 (2849, 0.22613350843332272),
 (3040, 0.22613350843332272),
 (3546, 0.22613350843332272),
 (3666, 0.22613350843332272),
 (4221, 0.22613350843332272),
 (4513, 0.22613350843332272),
 (6110, 0.22613350843332272),
 (7553, 0.22613350843332272),
 (7827, 0.22613350843332272),
 (9267, 0.22613350843332272),
 (9779, 0.22613350843332272),
 (10226, 0.22613350843332272),
 (10246, 0.22613350843332272),
 (9724, 0.22473328748774737),
 (1668, 0.2239570043823417),
 (5249, 0.2239570043823417),
 (5266, 0.2239570043823417),
 (7567, 0.2239570043823417),
 (8021, 0.2239570043823417),
 (9186, 0.2239570043823417),
 (9228, 0.2239570043823417),
 (5625, 0.22268088570756162),
 (2097, 0.22227711223719357),
 (471, 0.2201927530252721),
 (9551, 0.2201927530252721),
 (7468, 0.21989974856677125),
 (164, 0.2193817272381392),
 (966, 0.2193817272381392),
 (1192, 0.2193817272381392),
 (1529, 0.2193817272381392),
 (3113, 0.2193817272381392),
 (5155, 0.2193817272381392),
 (7017, 0.2193817272381392),
 (7460, 0.2193817272381392),
 (7614, 0.2193817272381392),
 (8321, 0.2193817272381392),
 (8704, 0.2193817272381392),
 (10536, 0.2193817272381392),
 (4682, 0.21661214442955293),
 (6607, 0.21661214442955293),
 (2321, 0.21622499104693418),
 (1061, 0.21320071635561047),
 (1421, 0.21320071635561047),
 (3120, 0.21320071635561047),
 (3446, 0.21320071635561047),
 (3511, 0.21320071635561047),
 (4642, 0.21320071635561047),
 (5829, 0.21320071635561047),
 (6342, 0.21320071635561047),
 (7537, 0.21320071635561047),
 (8128, 0.21320071635561047),
 (8346, 0.21320071635561047),
 (8897, 0.21320071635561047),
 (9195, 0.21320071635561047),
 (10625, 0.21320071635561047),
 (7399, 0.21320071635561044),
 (2092, 0.21320071635561041),
 (2685, 0.21320071635561041),
 (3329, 0.21320071635561041),
 (4228, 0.21320071635561041),
 (5268, 0.21320071635561041),
 (5716, 0.21320071635561041),
 (8470, 0.21320071635561041),
 (9190, 0.21320071635561041),
 (120, 0.2099455524325912),
 (5250, 0.2099455524325912),
 (7341, 0.2099455524325912),
 (8403, 0.2099455524325912),
 (9448, 0.2099455524325912),
 (54, 0.2075143391598224),
 (112, 0.2075143391598224),
 (301, 0.2075143391598224),
 (688, 0.2075143391598224),
 (1580, 0.2075143391598224),
 (1823, 0.2075143391598224),
 (2200, 0.2075143391598224),
 (2707, 0.2075143391598224),
 (3978, 0.2075143391598224),
 (4385, 0.2075143391598224),
 (4455, 0.2075143391598224),
 (5470, 0.2075143391598224),
 (8000, 0.2075143391598224),
 (9043, 0.2075143391598224),
 (9789, 0.2075143391598224),
 (9934, 0.2075143391598224),
 (10180, 0.2075143391598224),
 (10640, 0.2075143391598224),
 (1008, 0.20683507599800766),
 (4001, 0.20683507599800766),
 (9758, 0.20683507599800766),
 (2020, 0.20515248496555455),
 (8340, 0.20515248496555455),
 (8844, 0.20515248496555455),
 (8250, 0.2038588765750502),
 (817, 0.20225995873897262),
 (3373, 0.20225995873897262),
 (3770, 0.20225995873897262),
 (4052, 0.20225995873897262),
 (5022, 0.20225995873897262),
 (5449, 0.20225995873897262),
 (5477, 0.20225995873897262),
 (6044, 0.20225995873897262),
 (7494, 0.20225995873897262),
 (7497, 0.20225995873897262),
 (8241, 0.20225995873897262),
 (8570, 0.20225995873897262),
 (9781, 0.20225995873897262),
 (10555, 0.20225995873897262),
 (254, 0.20100756305184242),
 (1490, 0.20100756305184242),
 (1951, 0.20100756305184242),
 (2254, 0.20100756305184242),
 (3125, 0.20100756305184242),
 (3497, 0.20100756305184242),
 (3568, 0.20100756305184242),
 (4703, 0.20100756305184242),
 (4820, 0.20100756305184242),
 (6194, 0.20100756305184242),
 (6495, 0.20100756305184242),
 (6716, 0.20100756305184242),
 (6804, 0.20100756305184242),
 (7446, 0.20100756305184242),
 (9031, 0.20100756305184242),
 (9996, 0.20100756305184242),
 (38, 0.19977814746360806),
 (5568, 0.19827263883864388),
 (67, 0.1973855084879307),
 (108, 0.1973855084879307),
 (109, 0.1973855084879307),
 (647, 0.1973855084879307),
 (868, 0.1973855084879307),
 (962, 0.1973855084879307),
 (1124, 0.1973855084879307),
 (1518, 0.1973855084879307),
 (2615, 0.1973855084879307),
 (2892, 0.1973855084879307),
 (2973, 0.1973855084879307),
 (4320, 0.1973855084879307),
 (4386, 0.1973855084879307),
 (4634, 0.1973855084879307),
 (5696, 0.1973855084879307),
 (6263, 0.1973855084879307),
 (6720, 0.1973855084879307),
 (6753, 0.1973855084879307),
 (7034, 0.1973855084879307),
 (9326, 0.1973855084879307),
 (9599, 0.1973855084879307),
 (10027, 0.1973855084879307),
 (10244, 0.1973855084879307),
 (9152, 0.1956463952178074),
 (795, 0.19564639521780738),
 (2183, 0.19312181983410703),
 (2792, 0.19284730395996752),
 (59, 0.1928473039599675),
 (138, 0.1928473039599675),
 (1043, 0.1928473039599675),
 (1515, 0.1928473039599675),
 (1552, 0.1928473039599675),
 (1733, 0.1928473039599675),
 (2527, 0.1928473039599675),
 (3119, 0.1928473039599675),
 (4201, 0.1928473039599675),
 (4618, 0.1928473039599675),
 (5348, 0.1928473039599675),
 (5456, 0.1928473039599675),
 (6726, 0.1928473039599675),
 (7126, 0.1928473039599675),
 (7461, 0.1928473039599675),
 (8032, 0.1928473039599675),
 (9070, 0.1928473039599675),
 (249, 0.19069251784911848),
 (322, 0.19069251784911848),
 (2216, 0.19069251784911848),
 (2279, 0.19069251784911848),
 (3150, 0.19069251784911848),
 (3641, 0.19069251784911848),
 (4531, 0.19069251784911848),
 (6049, 0.19069251784911848),
 (6748, 0.19069251784911848),
 (6872, 0.19069251784911848),
 (8247, 0.19069251784911848),
 (8487, 0.19069251784911848),
 (10841, 0.19069251784911848),
 (1, 0.18993429409939658),
 (8847, 0.1896418623723042),
 (60, 0.18860838403857944),
 (568, 0.18860838403857944),
 (661, 0.18860838403857944),
 (916, 0.18860838403857944),
 (1109, 0.18860838403857944),
 (1544, 0.18860838403857944),
 (1952, 0.18860838403857944),
 (2445, 0.18860838403857944),
 (7664, 0.18860838403857944),
 (8544, 0.18860838403857944),
 (9259, 0.18860838403857944),
 (9496, 0.18860838403857944),
 (10252, 0.18860838403857944),
 (10365, 0.18860838403857944),
 (10601, 0.18860838403857944),
 (5635, 0.18835264373920446),
 (8069, 0.18835264373920446),
 (8680, 0.18835264373920446),
 (3556, 0.18609684207969418),
 (3952, 0.18609684207969415),
 (4313, 0.18609684207969415),
 (5315, 0.18609684207969415),
 (10761, 0.18609684207969415),
 (10427, 0.1856064674669238),
 (719, 0.18463723646899913),
 (786, 0.18463723646899913),
 (1418, 0.18463723646899913),
 (3622, 0.18463723646899913),
 (5336, 0.18463723646899913),
 (5541, 0.18463723646899913),
 (5721, 0.18463723646899913),
 (6256, 0.18463723646899913),
 (6615, 0.18463723646899913),
 (7688, 0.18463723646899913),
 (8124, 0.18463723646899913),
 (8677, 0.18463723646899913),
 (10036, 0.18463723646899913),
 (2574, 0.1841773671709393),
 (2904, 0.18392019594868114),
 (6601, 0.18392019594868114),
 (8325, 0.18392019594868114),
 (9196, 0.18392019594868114),
 (9215, 0.18392019594868114),
 (10763, 0.18181818181818185),
 (233, 0.18181818181818182),
 (710, 0.18181818181818182),
 (737, 0.18181818181818182),
 (1051, 0.18181818181818182),
 (1078, 0.18181818181818182),
 (1885, 0.18181818181818182),
 (2048, 0.18181818181818182),
 (2259, 0.18181818181818182),
 (2764, 0.18181818181818182),
 (2845, 0.18181818181818182),
 (3069, 0.18181818181818182),
 (3259, 0.18181818181818182),
 (4191, 0.18181818181818182),
 (4227, 0.18181818181818182),
 (4230, 0.18181818181818182),
 (4871, 0.18181818181818182),
 (5156, 0.18181818181818182),
 (5171, 0.18181818181818182),
 (5374, 0.18181818181818182),
 (5507, 0.18181818181818182),
 (5622, 0.18181818181818182),
 (5631, 0.18181818181818182),
 (5668, 0.18181818181818182),
 (5996, 0.18181818181818182),
 (6138, 0.18181818181818182),
 (6274, 0.18181818181818182),
 (6434, 0.18181818181818182),
 (7145, 0.18181818181818182),
 (7252, 0.18181818181818182),
 (10107, 0.18181818181818182),
 (86, 0.18090680674665818),
 (2201, 0.18090680674665818),
 (2669, 0.18090680674665818),
 (3137, 0.18090680674665818),
 (4177, 0.18090680674665818),
 (4397, 0.18090680674665818),
 (6484, 0.18090680674665818),
 (6488, 0.18090680674665818),
 (6576, 0.18090680674665818),
 (6684, 0.18090680674665818),
 (6732, 0.18090680674665818),
 (8945, 0.18090680674665818),
 (8981, 0.18090680674665818),
 (10850, 0.18090680674665818),
 (2353, 0.1797866299901979),
 (4993, 0.1797866299901979),
 (7583, 0.1797866299901979),
 (7795, 0.1797866299901979),
 (10382, 0.1797866299901979),
 (5866, 0.1796644508187709),
 (728, 0.17782168978975485),
 (2875, 0.17782168978975485),
 (5359, 0.17782168978975485),
 (5960, 0.17782168978975485),
 (10020, 0.17782168978975485),
 (10075, 0.17782168978975485),
 (1059, 0.1773937187967248),
 (1344, 0.1773937187967248),
 (1432, 0.1773937187967248),
 (4054, 0.1773937187967248),
 (4104, 0.1773937187967248),
 (5049, 0.1773937187967248),
 (5636, 0.1773937187967248),
 (5669, 0.1773937187967248),
 (6677, 0.1773937187967248),
 (6816, 0.1773937187967248),
 (7038, 0.1773937187967248),
 (8231, 0.1773937187967248),
 (8341, 0.1773937187967248),
 (6217, 0.175919798853417),
 (8288, 0.175919798853417),
 (8520, 0.175919798853417),
 (8892, 0.175919798853417),
 (5288, 0.17407765595569788),
 (487, 0.17407765595569785),
 (911, 0.17407765595569785),
 (1157, 0.17407765595569785),
 (1744, 0.17407765595569785),
 (1783, 0.17407765595569785),
 (1810, 0.17407765595569785),
 (2335, 0.17407765595569785),
 (2573, 0.17407765595569785),
 (2779, 0.17407765595569785),
 (2933, 0.17407765595569785),
 (2971, 0.17407765595569785),
 (3762, 0.17407765595569785),
 (4008, 0.17407765595569785),
 (4283, 0.17407765595569785),
 (4674, 0.17407765595569785),
 (4690, 0.17407765595569785),
 (5030, 0.17407765595569785),
 (5251, 0.17407765595569785),
 (5377, 0.17407765595569785),
 (5783, 0.17407765595569785),
 (6149, 0.17407765595569785),
 (6432, 0.17407765595569785),
 (7128, 0.17407765595569785),
 (7273, 0.17407765595569785),
 (7559, 0.17407765595569785),
 (7639, 0.17407765595569785),
 (7800, 0.17407765595569785),
 (7812, 0.17407765595569785),
 (8158, 0.17407765595569785),
 (8490, 0.17407765595569785),
 (9279, 0.17407765595569785),
 (9431, 0.17407765595569785),
 (9751, 0.17407765595569785),
 (9785, 0.17407765595569785),
 (10615, 0.17407765595569785),
 (5337, 0.17229219690157918),
 (6286, 0.17229219690157918),
 (10782, 0.17229219690157918),
 (9210, 0.17094086468945693),
 (1412, 0.1709408646894569),
 (1604, 0.1709408646894569),
 (1990, 0.1709408646894569),
 (2487, 0.1709408646894569),
 (2893, 0.1709408646894569),
 (3530, 0.1709408646894569),
 (4051, 0.1709408646894569),
 (5890, 0.1709408646894569),
 (6204, 0.1709408646894569),
 (7014, 0.1709408646894569),
 (8361, 0.1709408646894569),
 (9908, 0.1709408646894569),
 (10366, 0.1709408646894569),
 (5345, 0.16888013236829963),
 (5987, 0.1688801323682996),
 (8976, 0.1688801323682996),
 (730, 0.16854996561581054),
 (1597, 0.16796775328675628),
 (2671, 0.16796775328675628),
 (2878, 0.16796775328675628),
 (2953, 0.16796775328675628),
 (2991, 0.16796775328675628),
 (3695, 0.16796775328675628),
 (4315, 0.16796775328675628),
 (4324, 0.16796775328675628),
 (4774, 0.16796775328675628),
 (5282, 0.16796775328675628),
 (5683, 0.16796775328675628),
 (7312, 0.16796775328675628),
 (9458, 0.16796775328675628),
 (9955, 0.16796775328675628),
 (10602, 0.16796775328675628),
 (48, 0.16724840200141816),
 (111, 0.16724840200141816),
 (124, 0.16724840200141816),
 (137, 0.16724840200141816),
 (333, 0.16724840200141816),
 (677, 0.16724840200141816),
 (741, 0.16724840200141816),
 (876, 0.16724840200141816),
 (930, 0.16724840200141816),
 (946, 0.16724840200141816),
 (1028, 0.16724840200141816),
 (1445, 0.16724840200141816),
 (1692, 0.16724840200141816),
 (1856, 0.16724840200141816),
 (2133, 0.16724840200141816),
 (2698, 0.16724840200141816),
 (3514, 0.16724840200141816),
 (3537, 0.16724840200141816),
 (4454, 0.16724840200141816),
 (4745, 0.16724840200141816),
 (4859, 0.16724840200141816),
 (4983, 0.16724840200141816),
 (5078, 0.16724840200141816),
 (5307, 0.16724840200141816),
 (5448, 0.16724840200141816),
 (6279, 0.16724840200141816),
 (6329, 0.16724840200141816),
 (6407, 0.16724840200141816),
 (6813, 0.16724840200141816),
 (6913, 0.16724840200141816),
 (7111, 0.16724840200141816),
 (7430, 0.16724840200141816),
 (7641, 0.16724840200141816),
 (7702, 0.16724840200141816),
 (8107, 0.16724840200141816),
 (8139, 0.16724840200141816),
 (8273, 0.16724840200141816),
 (8314, 0.16724840200141816),
 (8755, 0.16724840200141816),
 (8841, 0.16724840200141816),
 (9227, 0.16724840200141816),
 (9901, 0.16724840200141816),
 (9945, 0.16724840200141816),
 (10150, 0.16724840200141816),
 (10410, 0.16724840200141816),
 (10622, 0.16724840200141816),
 (10799, 0.16724840200141816),
 (1993, 0.16566307331251645),
 (5043, 0.16566307331251645),
 (940, 0.1651445647689541),
 (1638, 0.1651445647689541),
 (2089, 0.1651445647689541),
 (2090, 0.1651445647689541),
 (2304, 0.1651445647689541),
 (4459, 0.1651445647689541),
 (5098, 0.1651445647689541),
 (5120, 0.1651445647689541),
 (6951, 0.1651445647689541),
 (7172, 0.1651445647689541),
 (8733, 0.1651445647689541),
 (8775, 0.1651445647689541),
 (10377, 0.1651445647689541),
 (1812, 0.16412198797244365),
 (3813, 0.16412198797244365),
 (4412, 0.16412198797244365),
 (8825, 0.16412198797244365),
 (5997, 0.16378532712978425),
 (5286, 0.16262312563634834),
 (3174, 0.1624591083221647),
 (4181, 0.1624591083221647),
 (5025, 0.1624591083221647),
 (5240, 0.1624591083221647),
 (7345, 0.1624591083221647),
 (8016, 0.1624591083221647),
 (8536, 0.1624591083221647),
 (8761, 0.1624591083221647),
 (10005, 0.1624591083221647),
 (285, 0.16116459280507606),
 (390, 0.16116459280507606),
 (1509, 0.16116459280507606),
 (1715, 0.16116459280507606),
 (1760, 0.16116459280507606),
 (2365, 0.16116459280507606),
 (3217, 0.16116459280507606),
 (3434, 0.16116459280507606),
 (3486, 0.16116459280507606),
 (3574, 0.16116459280507606),
 (3585, 0.16116459280507606),
 (3616, 0.16116459280507606),
 (4238, 0.16116459280507606),
 (4486, 0.16116459280507606),
 (4590, 0.16116459280507606),
 (5019, 0.16116459280507606),
 (5392, 0.16116459280507606),
 (5558, 0.16116459280507606),
 (5576, 0.16116459280507606),
 (5719, 0.16116459280507606),
 (7109, 0.16116459280507606),
 (7159, 0.16116459280507606),
 (7364, 0.16116459280507606),
 (8064, 0.16116459280507606),
 (8583, 0.16116459280507606),
 (8671, 0.16116459280507606),
 (8718, 0.16116459280507606),
 (9223, 0.16116459280507606),
 (9407, 0.16116459280507606),
 (9613, 0.16116459280507606),
 (9741, 0.16116459280507606),
 (9813, 0.16116459280507606),
 (9830, 0.16116459280507606),
 (9987, 0.16116459280507606),
 (10011, 0.16116459280507606),
 (10079, 0.16116459280507606),
 (10190, 0.16116459280507606),
 (10380, 0.16116459280507606),
 (478, 0.1599005372667078),
 (1791, 0.1599005372667078),
 (1871, 0.1599005372667078),
 (3826, 0.1599005372667078),
 (4453, 0.1599005372667078),
 (5291, 0.1599005372667078),
 (6238, 0.1599005372667078),
 (6592, 0.1599005372667078),
 (8079, 0.1599005372667078),
 (9078, 0.1599005372667078),
 (9873, 0.1599005372667078),
 (9940, 0.1599005372667078),
 (959, 0.1598006930251483),
 (3654, 0.15974461276617435),
 (4165, 0.15974461276617435),
 (5376, 0.15974461276617435),
 (7989, 0.15974461276617435),
 (10273, 0.15974461276617435),
 (4576, 0.15836151649297917),
 (5028, 0.15836151649297917),
 (2212, 0.1574591643244434),
 (2670, 0.1574591643244434),
 (2896, 0.1574591643244434),
 (2993, 0.1574591643244434),
 (3443, 0.1574591643244434),
 (5782, 0.1574591643244434),
 (6151, 0.1574591643244434),
 (7298, 0.1574591643244434),
 (8535, 0.1574591643244434),
 (8653, 0.1574591643244434),
 (8931, 0.1574591643244434),
 (9059, 0.1574591643244434),
 (10028, 0.1574591643244434),
 (10549, 0.1574591643244434),
 (10276, 0.15701373439577193),
 (84, 0.1556997888323046),
 (173, 0.1556997888323046),
 (356, 0.1556997888323046),
 (418, 0.1556997888323046),
 (432, 0.1556997888323046),
 (744, 0.1556997888323046),
 (802, 0.1556997888323046),
 (935, 0.1556997888323046),
 (979, 0.1556997888323046),
 (1385, 0.1556997888323046),
 (1799, 0.1556997888323046),
 (1908, 0.1556997888323046),
 (2043, 0.1556997888323046),

In [57]:
for i in distance[0:5]:
        print(movies.iloc[i[0]].original_title)
        print(i)

Furious 7
(4, 1.0000000000000002)
Savage Streets
(7949, 0.36563621206356534)
Fast & Furious 6
(5650, 0.3458572319330373)
Patriot Games
(8277, 0.3458572319330373)
Transit
(4757, 0.3344968040028364)

In [58]:
movies.iloc[4]

id                                                           168259
original_title                                            Furious 7
tags              Action|Crime|Thriller Deckard Shaw seeks reven...
Name: 4, dtype: object

In [59]:
similarity

array([[1.        , 0.2057378 , 0.19802951, ..., 0.        , 0.0758098 ,
        0.        ],
       [0.2057378 , 1.        , 0.12222647, ..., 0.        , 0.16376789,
        0.        ],
       [0.19802951, 0.12222647, 1.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.03573708,
        0.        ],
       [0.0758098 , 0.16376789, 0.        , ..., 0.03573708, 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.        ]])